# Generated by Django 5.0.6 on 2024-06-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=50, verbose_name='')),
                ('author_name', models.CharField(max_length=50, verbose_name='')),
                ('image_author', models.ImageField(upload_to='img/', verbose_name='')),
                ('image_book', models.ImageField(upload_to='img/', verbose_name='')),
                ('pages', models.IntegerField(default=100, verbose_name='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('retal_price_day', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('retal_period', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('active', models.BooleanField(default=True, verbose_name='')),
                ('status', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], max_length=50, verbose_name='')),
            ],
            options={
                'verbose_name': 'Books',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
