# Generated by Django 5.0.6 on 2024-06-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='author_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='books',
            name='image_author',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='books',
            name='image_book',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='books',
            name='pages',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='books',
            name='retal_period',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='books',
            name='retal_price_day',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='books',
            name='title_name',
            field=models.CharField(max_length=50),
        ),
    ]
