# Generated by Django 5.0.6 on 2024-06-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_books_active_alter_books_author_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cateogry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Cateogry',
                'verbose_name_plural': 'Cateogry',
            },
        ),
    ]
