# Generated by Django 5.0.6 on 2024-06-09 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_cateogry'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cateogry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lms.cateogry'),
            preserve_default=False,
        ),
    ]
