# Generated by Django 5.0.6 on 2024-06-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_books_cateogry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image_author',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
