# Generated by Django 5.0.6 on 2024-06-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_books_image_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image_book',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable'), ('rented', 'rented')], max_length=50),
        ),
    ]
