# Generated by Django 5.0.6 on 2024-06-09 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_books_image_book_alter_books_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='title_name',
            new_name='title_book',
        ),
    ]
