# Generated by Django 5.0.6 on 2024-06-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_rename_title_name_books_title_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='retal_period',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='retal_price_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
