# Generated by Django 5.0.6 on 2024-06-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_alter_books_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable'), ('rented', 'مستأجر')], max_length=50),
        ),
    ]
