# Generated by Django 5.0.6 on 2024-06-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_alter_books_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.CharField(choices=[('متاح', 'متاح'), ('غير متاح', 'غير متاح'), ('مستأجر', 'مستأجر')], max_length=50),
        ),
    ]
