# Generated by Django 4.2.13 on 2024-06-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_alter_books_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.CharField(choices=[('متاح', 'متاح'), ('غير متاح', 'غير متاح'), ('تأجير', 'تأجير')], max_length=50),
        ),
    ]
