# Generated by Django 4.2.13 on 2024-06-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_alter_books_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='retal_period',
            new_name='rental_period',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='retal_price_day',
            new_name='rental_price_day',
        ),
        migrations.AddField(
            model_name='books',
            name='total_period',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
