# Generated by Django 4.2.13 on 2024-06-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_rename_retal_period_books_rental_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='rental_period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
