# Generated by Django 4.2.13 on 2024-06-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0017_alter_books_rental_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='rental_period',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
