# Generated by Django 4.2.13 on 2024-06-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0018_alter_books_rental_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='rental_period',
            new_name='retal_period',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='rental_price_day',
            new_name='retal_price_day',
        ),
        migrations.RemoveField(
            model_name='books',
            name='total_period',
        ),
    ]
